//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancesPersonnelles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public int BudgetId { get; set; }
        public int GroupId { get; set; }
        public System.DateTime BudDate { get; set; }
        public double BudValue { get; set; }
        public string BudDescription { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
