//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancesPersonnelles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movement
    {
        public int MovementId { get; set; }
        public int GroupId { get; set; }
        public System.DateTime MovDate { get; set; }
        public double MovValue { get; set; }
        public string MovDescription { get; set; }
        public int AccountId { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Account Account { get; set; }
    }
}
